export enum CartTypes {
  ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL",

  GET_CART_SUCCESS = "GET_CART_SUCCESS",
  GET_CART_FAIL = "GET_CART_FAIL",

  DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS",
  DELETE_FROM_CART_FAIL = "DELETE_FROM_CART_FAIL",
}
