export enum ProductTypes {
  ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS",
  ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL",
}

export enum ViewProductTypes {
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL",
}
