export enum UserActionsTypes {
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  SIGNUP_FAIL = "SIGNUP_FAIL",
  CLEAR_ERRORS = "CLEAR_ERRORS",

  UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL",
}
